import constants

BTN_DICT = {}
BUTTONS_INFO_LIST = [('maroo_button',
                      constants.MAROON,
                      (40, constants.RECT_CENTER_Y, 25, 25)),
                     ('crimson_button',
                      constants.CRIMSON,
                      (70, constants.RECT_CENTER_Y, 25, 25)),
                     ('red_button',
                      constants.RED,
                      (100, constants.RECT_CENTER_Y, 25, 25)),
                     ('salmon_button',
                      constants.SALMON,
                      (130, constants.RECT_CENTER_Y, 25, 25)),
                     ('orange',
                      constants.ORANGE,
                      (160, constants.RECT_CENTER_Y, 25, 25)),
                     ('gold_button',
                      constants.GOLD,
                      (190, constants.RECT_CENTER_Y, 25, 25)),
                     ('yellow_button',
                      constants.YELLOW,
                      (220, constants.RECT_CENTER_Y, 25, 25)),
                     ('olive_button',
                      constants.OLIVE,
                      (250, constants.RECT_CENTER_Y, 25, 25)),
                     ('dark_green_button',
                      constants.DARK_GREEN,
                      (40, constants.RECT_CENTER_Y * 2, 25, 25)),
                     ('green_button',
                      constants.GREEN,
                      (70, constants.RECT_CENTER_Y * 2, 25, 25)),
                     ('spring_green_button',
                      constants.SPRING_GREEN,
                      (100, constants.RECT_CENTER_Y * 2, 25, 25)),
                     ('aqua',
                      constants.AQUA,
                      (130, constants.RECT_CENTER_Y * 2, 25, 25)),
                     ('blue',
                      constants.BLUE,
                      (160, constants.RECT_CENTER_Y * 2, 25, 25)),
                     ('purple_button',
                      constants.PURPLE,
                      (190, constants.RECT_CENTER_Y * 2, 25, 25)),
                     ('brown_button',
                      constants.BROWN,
                      (220, constants.RECT_CENTER_Y * 2, 25, 25)),
                     ('black_button',
                      constants.BLACK,
                      (250, constants.RECT_CENTER_Y * 2, 25, 25))
                     ]
IMG_BTN_DICT = {}
IMG_BUTTONS_INFO_LIST = [('erase_button',
                          constants.PATH_ERASE_BTN,
                          (990, constants.RECT_CENTER_Y, 50, 50)),
                         ('arrow_up_button',
                          constants.PATH_ARROW_UP,
                          (1050, constants.RECT_CENTER_Y, 50, 50)),
                         ('arrow_down_button',
                          constants.PATH_ARROW_DOWN,
                          (1110, constants.RECT_CENTER_Y, 50, 50)),
                         ('palette_button',
                          constants.PATH_PALETTE,
                          (930, constants.RECT_CENTER_Y,  50, 50))
                         ]
